#pragma config(Sensor, S1,     bump,           sensorTouch)
#pragma config(Sensor, S2,     beam,           sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#define DEGREES_TO_RAISE_ARM 270

int degrees_to_raise_arm; //set this using calibrateArm
bool armIsRaised; //this will be true if the arm is raised.
bool armLock; //this will be true if a function is moving the arm.
int lightProportion;
int max_light;
int min_light;

void calibrateArm();
task lowerArm();
task raiseArm();
task detectLine();
task moveOnLine();

task main()
{
	calibrateArm();

	StartTask(detectLine);
	StartTask(moveOnLine);

	while(true);
}

void calibrateArm() {
	motor[motorA] = -100;
	while(!SensorValue(bump));
	motor[motorA] = 0;
	nMotorEncoder[motorA] = 0;
	motor[motorA] = +20;
	wait1Msec(2000);
	degrees_to_raise_arm = abs(nMotorEncoder[motorA]) - 10;
	motor[motorA] = 0;
	armIsRaised = true;
	armLock = false;
}

task lowerArm() {
	if (!armIsRaised)
		return;
	while(armLock);
	armLock = true;
	motor[motorA] = -100;
	while(!SensorValue(bump));
	motor[motorA] = 0;
	nMotorEncoder[motorA] = 0;
	armIsRaised = false;
	armLock = false;
}

task raiseArm(){
	if (armIsRaised)
		return;
	while(armLock);
	armLock = true;
	motor[motorA] = 100;
	while(nMotorEncoder[motorA] < degrees_to_raise_arm);
	motor[motorA] = 0;
	armIsRaised = false;
	armLock = false;
}

task detectLine() {
	StartTask(lowerArm);
	while(true) {
		lightProportion = SensorValue(beam);

	}
}

task moveOnLine() {
	while(true) {
			motor[motorB] = (lightProportion > 50) ? -100 : 0;
			motor[motorC] = (lightProportion <= 50) ? -100 : 0;
	}
}
