#pragma config(Sensor, S3,     boom,           sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "MotorControl.c"
task main()
{
while(true) {
	nSyncedMotors = synchBC;
	nSyncedTurnRatio = 100;
	motor[motorB] = 100;
	while(!SensorValue(boom));
	goCM(-10);

}


}
